# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thiago/Desktop/Fiuba/Taller1/tp-final-taller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thiago/Desktop/Fiuba/Taller1/tp-final-taller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiago/Desktop/Fiuba/Taller1/tp-final-taller/CMakeFiles /home/thiago/Desktop/Fiuba/Taller1/tp-final-taller/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiago/Desktop/Fiuba/Taller1/tp-final-taller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WolfensteinTest

# Build rule for target.
WolfensteinTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WolfensteinTest
.PHONY : WolfensteinTest

# fast build rule for target.
WolfensteinTest/fast:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/build
.PHONY : WolfensteinTest/fast

#=============================================================================
# Target rules for targets named ServerMain

# Build rule for target.
ServerMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ServerMain
.PHONY : ServerMain

# fast build rule for target.
ServerMain/fast:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/build
.PHONY : ServerMain/fast

common/src/Socket/SocketCommunication.o: common/src/Socket/SocketCommunication.cpp.o

.PHONY : common/src/Socket/SocketCommunication.o

# target to build an object file
common/src/Socket/SocketCommunication.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketCommunication.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketCommunication.cpp.o
.PHONY : common/src/Socket/SocketCommunication.cpp.o

common/src/Socket/SocketCommunication.i: common/src/Socket/SocketCommunication.cpp.i

.PHONY : common/src/Socket/SocketCommunication.i

# target to preprocess a source file
common/src/Socket/SocketCommunication.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketCommunication.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketCommunication.cpp.i
.PHONY : common/src/Socket/SocketCommunication.cpp.i

common/src/Socket/SocketCommunication.s: common/src/Socket/SocketCommunication.cpp.s

.PHONY : common/src/Socket/SocketCommunication.s

# target to generate assembly for a file
common/src/Socket/SocketCommunication.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketCommunication.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketCommunication.cpp.s
.PHONY : common/src/Socket/SocketCommunication.cpp.s

common/src/Socket/SocketListener.o: common/src/Socket/SocketListener.cpp.o

.PHONY : common/src/Socket/SocketListener.o

# target to build an object file
common/src/Socket/SocketListener.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketListener.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketListener.cpp.o
.PHONY : common/src/Socket/SocketListener.cpp.o

common/src/Socket/SocketListener.i: common/src/Socket/SocketListener.cpp.i

.PHONY : common/src/Socket/SocketListener.i

# target to preprocess a source file
common/src/Socket/SocketListener.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketListener.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketListener.cpp.i
.PHONY : common/src/Socket/SocketListener.cpp.i

common/src/Socket/SocketListener.s: common/src/Socket/SocketListener.cpp.s

.PHONY : common/src/Socket/SocketListener.s

# target to generate assembly for a file
common/src/Socket/SocketListener.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Socket/SocketListener.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Socket/SocketListener.cpp.s
.PHONY : common/src/Socket/SocketListener.cpp.s

common/src/Thread/Thread.o: common/src/Thread/Thread.cpp.o

.PHONY : common/src/Thread/Thread.o

# target to build an object file
common/src/Thread/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Thread/Thread.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Thread/Thread.cpp.o
.PHONY : common/src/Thread/Thread.cpp.o

common/src/Thread/Thread.i: common/src/Thread/Thread.cpp.i

.PHONY : common/src/Thread/Thread.i

# target to preprocess a source file
common/src/Thread/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Thread/Thread.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Thread/Thread.cpp.i
.PHONY : common/src/Thread/Thread.cpp.i

common/src/Thread/Thread.s: common/src/Thread/Thread.cpp.s

.PHONY : common/src/Thread/Thread.s

# target to generate assembly for a file
common/src/Thread/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/common/src/Thread/Thread.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/common/src/Thread/Thread.cpp.s
.PHONY : common/src/Thread/Thread.cpp.s

server/src/Control/Command/PlayerMove.o: server/src/Control/Command/PlayerMove.cpp.o

.PHONY : server/src/Control/Command/PlayerMove.o

# target to build an object file
server/src/Control/Command/PlayerMove.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Command/PlayerMove.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Command/PlayerMove.cpp.o
.PHONY : server/src/Control/Command/PlayerMove.cpp.o

server/src/Control/Command/PlayerMove.i: server/src/Control/Command/PlayerMove.cpp.i

.PHONY : server/src/Control/Command/PlayerMove.i

# target to preprocess a source file
server/src/Control/Command/PlayerMove.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Command/PlayerMove.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Command/PlayerMove.cpp.i
.PHONY : server/src/Control/Command/PlayerMove.cpp.i

server/src/Control/Command/PlayerMove.s: server/src/Control/Command/PlayerMove.cpp.s

.PHONY : server/src/Control/Command/PlayerMove.s

# target to generate assembly for a file
server/src/Control/Command/PlayerMove.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Command/PlayerMove.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Command/PlayerMove.cpp.s
.PHONY : server/src/Control/Command/PlayerMove.cpp.s

server/src/Control/Notification/PlayerConnected.o: server/src/Control/Notification/PlayerConnected.cpp.o

.PHONY : server/src/Control/Notification/PlayerConnected.o

# target to build an object file
server/src/Control/Notification/PlayerConnected.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerConnected.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerConnected.cpp.o
.PHONY : server/src/Control/Notification/PlayerConnected.cpp.o

server/src/Control/Notification/PlayerConnected.i: server/src/Control/Notification/PlayerConnected.cpp.i

.PHONY : server/src/Control/Notification/PlayerConnected.i

# target to preprocess a source file
server/src/Control/Notification/PlayerConnected.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerConnected.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerConnected.cpp.i
.PHONY : server/src/Control/Notification/PlayerConnected.cpp.i

server/src/Control/Notification/PlayerConnected.s: server/src/Control/Notification/PlayerConnected.cpp.s

.PHONY : server/src/Control/Notification/PlayerConnected.s

# target to generate assembly for a file
server/src/Control/Notification/PlayerConnected.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerConnected.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerConnected.cpp.s
.PHONY : server/src/Control/Notification/PlayerConnected.cpp.s

server/src/Control/Notification/PlayerDisconnect.o: server/src/Control/Notification/PlayerDisconnect.cpp.o

.PHONY : server/src/Control/Notification/PlayerDisconnect.o

# target to build an object file
server/src/Control/Notification/PlayerDisconnect.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerDisconnect.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerDisconnect.cpp.o
.PHONY : server/src/Control/Notification/PlayerDisconnect.cpp.o

server/src/Control/Notification/PlayerDisconnect.i: server/src/Control/Notification/PlayerDisconnect.cpp.i

.PHONY : server/src/Control/Notification/PlayerDisconnect.i

# target to preprocess a source file
server/src/Control/Notification/PlayerDisconnect.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerDisconnect.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerDisconnect.cpp.i
.PHONY : server/src/Control/Notification/PlayerDisconnect.cpp.i

server/src/Control/Notification/PlayerDisconnect.s: server/src/Control/Notification/PlayerDisconnect.cpp.s

.PHONY : server/src/Control/Notification/PlayerDisconnect.s

# target to generate assembly for a file
server/src/Control/Notification/PlayerDisconnect.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerDisconnect.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerDisconnect.cpp.s
.PHONY : server/src/Control/Notification/PlayerDisconnect.cpp.s

server/src/Control/Notification/PlayerUpdatePosition.o: server/src/Control/Notification/PlayerUpdatePosition.cpp.o

.PHONY : server/src/Control/Notification/PlayerUpdatePosition.o

# target to build an object file
server/src/Control/Notification/PlayerUpdatePosition.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.o
.PHONY : server/src/Control/Notification/PlayerUpdatePosition.cpp.o

server/src/Control/Notification/PlayerUpdatePosition.i: server/src/Control/Notification/PlayerUpdatePosition.cpp.i

.PHONY : server/src/Control/Notification/PlayerUpdatePosition.i

# target to preprocess a source file
server/src/Control/Notification/PlayerUpdatePosition.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.i
.PHONY : server/src/Control/Notification/PlayerUpdatePosition.cpp.i

server/src/Control/Notification/PlayerUpdatePosition.s: server/src/Control/Notification/PlayerUpdatePosition.cpp.s

.PHONY : server/src/Control/Notification/PlayerUpdatePosition.s

# target to generate assembly for a file
server/src/Control/Notification/PlayerUpdatePosition.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Control/Notification/PlayerUpdatePosition.cpp.s
.PHONY : server/src/Control/Notification/PlayerUpdatePosition.cpp.s

server/src/Match/Engine.o: server/src/Match/Engine.cpp.o

.PHONY : server/src/Match/Engine.o

# target to build an object file
server/src/Match/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Engine.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Engine.cpp.o
.PHONY : server/src/Match/Engine.cpp.o

server/src/Match/Engine.i: server/src/Match/Engine.cpp.i

.PHONY : server/src/Match/Engine.i

# target to preprocess a source file
server/src/Match/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Engine.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Engine.cpp.i
.PHONY : server/src/Match/Engine.cpp.i

server/src/Match/Engine.s: server/src/Match/Engine.cpp.s

.PHONY : server/src/Match/Engine.s

# target to generate assembly for a file
server/src/Match/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Engine.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Engine.cpp.s
.PHONY : server/src/Match/Engine.cpp.s

server/src/Match/Match.o: server/src/Match/Match.cpp.o

.PHONY : server/src/Match/Match.o

# target to build an object file
server/src/Match/Match.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Match.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Match.cpp.o
.PHONY : server/src/Match/Match.cpp.o

server/src/Match/Match.i: server/src/Match/Match.cpp.i

.PHONY : server/src/Match/Match.i

# target to preprocess a source file
server/src/Match/Match.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Match.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Match.cpp.i
.PHONY : server/src/Match/Match.cpp.i

server/src/Match/Match.s: server/src/Match/Match.cpp.s

.PHONY : server/src/Match/Match.s

# target to generate assembly for a file
server/src/Match/Match.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/Match.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/Match.cpp.s
.PHONY : server/src/Match/Match.cpp.s

server/src/Match/MatchList.o: server/src/Match/MatchList.cpp.o

.PHONY : server/src/Match/MatchList.o

# target to build an object file
server/src/Match/MatchList.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/MatchList.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/MatchList.cpp.o
.PHONY : server/src/Match/MatchList.cpp.o

server/src/Match/MatchList.i: server/src/Match/MatchList.cpp.i

.PHONY : server/src/Match/MatchList.i

# target to preprocess a source file
server/src/Match/MatchList.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/MatchList.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/MatchList.cpp.i
.PHONY : server/src/Match/MatchList.cpp.i

server/src/Match/MatchList.s: server/src/Match/MatchList.cpp.s

.PHONY : server/src/Match/MatchList.s

# target to generate assembly for a file
server/src/Match/MatchList.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Match/MatchList.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Match/MatchList.cpp.s
.PHONY : server/src/Match/MatchList.cpp.s

server/src/Model/Game/Game.o: server/src/Model/Game/Game.cpp.o

.PHONY : server/src/Model/Game/Game.o

# target to build an object file
server/src/Model/Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Game/Game.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Game/Game.cpp.o
.PHONY : server/src/Model/Game/Game.cpp.o

server/src/Model/Game/Game.i: server/src/Model/Game/Game.cpp.i

.PHONY : server/src/Model/Game/Game.i

# target to preprocess a source file
server/src/Model/Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Game/Game.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Game/Game.cpp.i
.PHONY : server/src/Model/Game/Game.cpp.i

server/src/Model/Game/Game.s: server/src/Model/Game/Game.cpp.s

.PHONY : server/src/Model/Game/Game.s

# target to generate assembly for a file
server/src/Model/Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Game/Game.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Game/Game.cpp.s
.PHONY : server/src/Model/Game/Game.cpp.s

server/src/Model/Item/Ammo.o: server/src/Model/Item/Ammo.cpp.o

.PHONY : server/src/Model/Item/Ammo.o

# target to build an object file
server/src/Model/Item/Ammo.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Ammo.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Ammo.cpp.o
.PHONY : server/src/Model/Item/Ammo.cpp.o

server/src/Model/Item/Ammo.i: server/src/Model/Item/Ammo.cpp.i

.PHONY : server/src/Model/Item/Ammo.i

# target to preprocess a source file
server/src/Model/Item/Ammo.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Ammo.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Ammo.cpp.i
.PHONY : server/src/Model/Item/Ammo.cpp.i

server/src/Model/Item/Ammo.s: server/src/Model/Item/Ammo.cpp.s

.PHONY : server/src/Model/Item/Ammo.s

# target to generate assembly for a file
server/src/Model/Item/Ammo.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Ammo.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Ammo.cpp.s
.PHONY : server/src/Model/Item/Ammo.cpp.s

server/src/Model/Item/Blood.o: server/src/Model/Item/Blood.cpp.o

.PHONY : server/src/Model/Item/Blood.o

# target to build an object file
server/src/Model/Item/Blood.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Blood.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Blood.cpp.o
.PHONY : server/src/Model/Item/Blood.cpp.o

server/src/Model/Item/Blood.i: server/src/Model/Item/Blood.cpp.i

.PHONY : server/src/Model/Item/Blood.i

# target to preprocess a source file
server/src/Model/Item/Blood.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Blood.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Blood.cpp.i
.PHONY : server/src/Model/Item/Blood.cpp.i

server/src/Model/Item/Blood.s: server/src/Model/Item/Blood.cpp.s

.PHONY : server/src/Model/Item/Blood.s

# target to generate assembly for a file
server/src/Model/Item/Blood.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Blood.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Blood.cpp.s
.PHONY : server/src/Model/Item/Blood.cpp.s

server/src/Model/Item/Chest.o: server/src/Model/Item/Chest.cpp.o

.PHONY : server/src/Model/Item/Chest.o

# target to build an object file
server/src/Model/Item/Chest.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Chest.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Chest.cpp.o
.PHONY : server/src/Model/Item/Chest.cpp.o

server/src/Model/Item/Chest.i: server/src/Model/Item/Chest.cpp.i

.PHONY : server/src/Model/Item/Chest.i

# target to preprocess a source file
server/src/Model/Item/Chest.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Chest.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Chest.cpp.i
.PHONY : server/src/Model/Item/Chest.cpp.i

server/src/Model/Item/Chest.s: server/src/Model/Item/Chest.cpp.s

.PHONY : server/src/Model/Item/Chest.s

# target to generate assembly for a file
server/src/Model/Item/Chest.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Chest.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Chest.cpp.s
.PHONY : server/src/Model/Item/Chest.cpp.s

server/src/Model/Item/Cross.o: server/src/Model/Item/Cross.cpp.o

.PHONY : server/src/Model/Item/Cross.o

# target to build an object file
server/src/Model/Item/Cross.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cross.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cross.cpp.o
.PHONY : server/src/Model/Item/Cross.cpp.o

server/src/Model/Item/Cross.i: server/src/Model/Item/Cross.cpp.i

.PHONY : server/src/Model/Item/Cross.i

# target to preprocess a source file
server/src/Model/Item/Cross.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cross.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cross.cpp.i
.PHONY : server/src/Model/Item/Cross.cpp.i

server/src/Model/Item/Cross.s: server/src/Model/Item/Cross.cpp.s

.PHONY : server/src/Model/Item/Cross.s

# target to generate assembly for a file
server/src/Model/Item/Cross.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cross.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cross.cpp.s
.PHONY : server/src/Model/Item/Cross.cpp.s

server/src/Model/Item/Crown.o: server/src/Model/Item/Crown.cpp.o

.PHONY : server/src/Model/Item/Crown.o

# target to build an object file
server/src/Model/Item/Crown.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Crown.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Crown.cpp.o
.PHONY : server/src/Model/Item/Crown.cpp.o

server/src/Model/Item/Crown.i: server/src/Model/Item/Crown.cpp.i

.PHONY : server/src/Model/Item/Crown.i

# target to preprocess a source file
server/src/Model/Item/Crown.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Crown.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Crown.cpp.i
.PHONY : server/src/Model/Item/Crown.cpp.i

server/src/Model/Item/Crown.s: server/src/Model/Item/Crown.cpp.s

.PHONY : server/src/Model/Item/Crown.s

# target to generate assembly for a file
server/src/Model/Item/Crown.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Crown.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Crown.cpp.s
.PHONY : server/src/Model/Item/Crown.cpp.s

server/src/Model/Item/Cup.o: server/src/Model/Item/Cup.cpp.o

.PHONY : server/src/Model/Item/Cup.o

# target to build an object file
server/src/Model/Item/Cup.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cup.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cup.cpp.o
.PHONY : server/src/Model/Item/Cup.cpp.o

server/src/Model/Item/Cup.i: server/src/Model/Item/Cup.cpp.i

.PHONY : server/src/Model/Item/Cup.i

# target to preprocess a source file
server/src/Model/Item/Cup.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cup.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cup.cpp.i
.PHONY : server/src/Model/Item/Cup.cpp.i

server/src/Model/Item/Cup.s: server/src/Model/Item/Cup.cpp.s

.PHONY : server/src/Model/Item/Cup.s

# target to generate assembly for a file
server/src/Model/Item/Cup.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Cup.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Cup.cpp.s
.PHONY : server/src/Model/Item/Cup.cpp.s

server/src/Model/Item/Food.o: server/src/Model/Item/Food.cpp.o

.PHONY : server/src/Model/Item/Food.o

# target to build an object file
server/src/Model/Item/Food.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Food.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Food.cpp.o
.PHONY : server/src/Model/Item/Food.cpp.o

server/src/Model/Item/Food.i: server/src/Model/Item/Food.cpp.i

.PHONY : server/src/Model/Item/Food.i

# target to preprocess a source file
server/src/Model/Item/Food.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Food.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Food.cpp.i
.PHONY : server/src/Model/Item/Food.cpp.i

server/src/Model/Item/Food.s: server/src/Model/Item/Food.cpp.s

.PHONY : server/src/Model/Item/Food.s

# target to generate assembly for a file
server/src/Model/Item/Food.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Food.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Food.cpp.s
.PHONY : server/src/Model/Item/Food.cpp.s

server/src/Model/Item/Item.o: server/src/Model/Item/Item.cpp.o

.PHONY : server/src/Model/Item/Item.o

# target to build an object file
server/src/Model/Item/Item.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Item.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Item.cpp.o
.PHONY : server/src/Model/Item/Item.cpp.o

server/src/Model/Item/Item.i: server/src/Model/Item/Item.cpp.i

.PHONY : server/src/Model/Item/Item.i

# target to preprocess a source file
server/src/Model/Item/Item.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Item.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Item.cpp.i
.PHONY : server/src/Model/Item/Item.cpp.i

server/src/Model/Item/Item.s: server/src/Model/Item/Item.cpp.s

.PHONY : server/src/Model/Item/Item.s

# target to generate assembly for a file
server/src/Model/Item/Item.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Item.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Item.cpp.s
.PHONY : server/src/Model/Item/Item.cpp.s

server/src/Model/Item/ItemDrop/ItemDrop.o: server/src/Model/Item/ItemDrop/ItemDrop.cpp.o

.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.o

# target to build an object file
server/src/Model/Item/ItemDrop/ItemDrop.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.o
.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.cpp.o

server/src/Model/Item/ItemDrop/ItemDrop.i: server/src/Model/Item/ItemDrop/ItemDrop.cpp.i

.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.i

# target to preprocess a source file
server/src/Model/Item/ItemDrop/ItemDrop.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.i
.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.cpp.i

server/src/Model/Item/ItemDrop/ItemDrop.s: server/src/Model/Item/ItemDrop/ItemDrop.cpp.s

.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.s

# target to generate assembly for a file
server/src/Model/Item/ItemDrop/ItemDrop.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/ItemDrop/ItemDrop.cpp.s
.PHONY : server/src/Model/Item/ItemDrop/ItemDrop.cpp.s

server/src/Model/Item/Key.o: server/src/Model/Item/Key.cpp.o

.PHONY : server/src/Model/Item/Key.o

# target to build an object file
server/src/Model/Item/Key.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Key.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Key.cpp.o
.PHONY : server/src/Model/Item/Key.cpp.o

server/src/Model/Item/Key.i: server/src/Model/Item/Key.cpp.i

.PHONY : server/src/Model/Item/Key.i

# target to preprocess a source file
server/src/Model/Item/Key.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Key.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Key.cpp.i
.PHONY : server/src/Model/Item/Key.cpp.i

server/src/Model/Item/Key.s: server/src/Model/Item/Key.cpp.s

.PHONY : server/src/Model/Item/Key.s

# target to generate assembly for a file
server/src/Model/Item/Key.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Key.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Key.cpp.s
.PHONY : server/src/Model/Item/Key.cpp.s

server/src/Model/Item/MedKit.o: server/src/Model/Item/MedKit.cpp.o

.PHONY : server/src/Model/Item/MedKit.o

# target to build an object file
server/src/Model/Item/MedKit.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/MedKit.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/MedKit.cpp.o
.PHONY : server/src/Model/Item/MedKit.cpp.o

server/src/Model/Item/MedKit.i: server/src/Model/Item/MedKit.cpp.i

.PHONY : server/src/Model/Item/MedKit.i

# target to preprocess a source file
server/src/Model/Item/MedKit.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/MedKit.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/MedKit.cpp.i
.PHONY : server/src/Model/Item/MedKit.cpp.i

server/src/Model/Item/MedKit.s: server/src/Model/Item/MedKit.cpp.s

.PHONY : server/src/Model/Item/MedKit.s

# target to generate assembly for a file
server/src/Model/Item/MedKit.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/MedKit.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/MedKit.cpp.s
.PHONY : server/src/Model/Item/MedKit.cpp.s

server/src/Model/Item/Weapon/Weapon.o: server/src/Model/Item/Weapon/Weapon.cpp.o

.PHONY : server/src/Model/Item/Weapon/Weapon.o

# target to build an object file
server/src/Model/Item/Weapon/Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Weapon/Weapon.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Weapon/Weapon.cpp.o
.PHONY : server/src/Model/Item/Weapon/Weapon.cpp.o

server/src/Model/Item/Weapon/Weapon.i: server/src/Model/Item/Weapon/Weapon.cpp.i

.PHONY : server/src/Model/Item/Weapon/Weapon.i

# target to preprocess a source file
server/src/Model/Item/Weapon/Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Weapon/Weapon.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Weapon/Weapon.cpp.i
.PHONY : server/src/Model/Item/Weapon/Weapon.cpp.i

server/src/Model/Item/Weapon/Weapon.s: server/src/Model/Item/Weapon/Weapon.cpp.s

.PHONY : server/src/Model/Item/Weapon/Weapon.s

# target to generate assembly for a file
server/src/Model/Item/Weapon/Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Item/Weapon/Weapon.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Item/Weapon/Weapon.cpp.s
.PHONY : server/src/Model/Item/Weapon/Weapon.cpp.s

server/src/Model/Player/Player.o: server/src/Model/Player/Player.cpp.o

.PHONY : server/src/Model/Player/Player.o

# target to build an object file
server/src/Model/Player/Player.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Player/Player.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Player/Player.cpp.o
.PHONY : server/src/Model/Player/Player.cpp.o

server/src/Model/Player/Player.i: server/src/Model/Player/Player.cpp.i

.PHONY : server/src/Model/Player/Player.i

# target to preprocess a source file
server/src/Model/Player/Player.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Player/Player.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Player/Player.cpp.i
.PHONY : server/src/Model/Player/Player.cpp.i

server/src/Model/Player/Player.s: server/src/Model/Player/Player.cpp.s

.PHONY : server/src/Model/Player/Player.s

# target to generate assembly for a file
server/src/Model/Player/Player.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Model/Player/Player.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Model/Player/Player.cpp.s
.PHONY : server/src/Model/Player/Player.cpp.s

server/src/Server/ClientAccepter.o: server/src/Server/ClientAccepter.cpp.o

.PHONY : server/src/Server/ClientAccepter.o

# target to build an object file
server/src/Server/ClientAccepter.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientAccepter.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientAccepter.cpp.o
.PHONY : server/src/Server/ClientAccepter.cpp.o

server/src/Server/ClientAccepter.i: server/src/Server/ClientAccepter.cpp.i

.PHONY : server/src/Server/ClientAccepter.i

# target to preprocess a source file
server/src/Server/ClientAccepter.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientAccepter.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientAccepter.cpp.i
.PHONY : server/src/Server/ClientAccepter.cpp.i

server/src/Server/ClientAccepter.s: server/src/Server/ClientAccepter.cpp.s

.PHONY : server/src/Server/ClientAccepter.s

# target to generate assembly for a file
server/src/Server/ClientAccepter.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientAccepter.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientAccepter.cpp.s
.PHONY : server/src/Server/ClientAccepter.cpp.s

server/src/Server/ClientCommunication.o: server/src/Server/ClientCommunication.cpp.o

.PHONY : server/src/Server/ClientCommunication.o

# target to build an object file
server/src/Server/ClientCommunication.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientCommunication.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientCommunication.cpp.o
.PHONY : server/src/Server/ClientCommunication.cpp.o

server/src/Server/ClientCommunication.i: server/src/Server/ClientCommunication.cpp.i

.PHONY : server/src/Server/ClientCommunication.i

# target to preprocess a source file
server/src/Server/ClientCommunication.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientCommunication.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientCommunication.cpp.i
.PHONY : server/src/Server/ClientCommunication.cpp.i

server/src/Server/ClientCommunication.s: server/src/Server/ClientCommunication.cpp.s

.PHONY : server/src/Server/ClientCommunication.s

# target to generate assembly for a file
server/src/Server/ClientCommunication.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ClientCommunication.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ClientCommunication.cpp.s
.PHONY : server/src/Server/ClientCommunication.cpp.s

server/src/Server/ConnectionHandler.o: server/src/Server/ConnectionHandler.cpp.o

.PHONY : server/src/Server/ConnectionHandler.o

# target to build an object file
server/src/Server/ConnectionHandler.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ConnectionHandler.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ConnectionHandler.cpp.o
.PHONY : server/src/Server/ConnectionHandler.cpp.o

server/src/Server/ConnectionHandler.i: server/src/Server/ConnectionHandler.cpp.i

.PHONY : server/src/Server/ConnectionHandler.i

# target to preprocess a source file
server/src/Server/ConnectionHandler.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ConnectionHandler.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ConnectionHandler.cpp.i
.PHONY : server/src/Server/ConnectionHandler.cpp.i

server/src/Server/ConnectionHandler.s: server/src/Server/ConnectionHandler.cpp.s

.PHONY : server/src/Server/ConnectionHandler.s

# target to generate assembly for a file
server/src/Server/ConnectionHandler.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/ConnectionHandler.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/ConnectionHandler.cpp.s
.PHONY : server/src/Server/ConnectionHandler.cpp.s

server/src/Server/Server.o: server/src/Server/Server.cpp.o

.PHONY : server/src/Server/Server.o

# target to build an object file
server/src/Server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/Server.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/Server.cpp.o
.PHONY : server/src/Server/Server.cpp.o

server/src/Server/Server.i: server/src/Server/Server.cpp.i

.PHONY : server/src/Server/Server.i

# target to preprocess a source file
server/src/Server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/Server.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/Server.cpp.i
.PHONY : server/src/Server/Server.cpp.i

server/src/Server/Server.s: server/src/Server/Server.cpp.s

.PHONY : server/src/Server/Server.s

# target to generate assembly for a file
server/src/Server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/server/src/Server/Server.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/server/src/Server/Server.cpp.s
.PHONY : server/src/Server/Server.cpp.s

serverMain.o: serverMain.cpp.o

.PHONY : serverMain.o

# target to build an object file
serverMain.cpp.o:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/serverMain.cpp.o
.PHONY : serverMain.cpp.o

serverMain.i: serverMain.cpp.i

.PHONY : serverMain.i

# target to preprocess a source file
serverMain.cpp.i:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/serverMain.cpp.i
.PHONY : serverMain.cpp.i

serverMain.s: serverMain.cpp.s

.PHONY : serverMain.s

# target to generate assembly for a file
serverMain.cpp.s:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/serverMain.cpp.s
.PHONY : serverMain.cpp.s

test/CPPUnit.o: test/CPPUnit.cpp.o

.PHONY : test/CPPUnit.o

# target to build an object file
test/CPPUnit.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/CPPUnit.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/test/CPPUnit.cpp.o
.PHONY : test/CPPUnit.cpp.o

test/CPPUnit.i: test/CPPUnit.cpp.i

.PHONY : test/CPPUnit.i

# target to preprocess a source file
test/CPPUnit.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/CPPUnit.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/test/CPPUnit.cpp.i
.PHONY : test/CPPUnit.cpp.i

test/CPPUnit.s: test/CPPUnit.cpp.s

.PHONY : test/CPPUnit.s

# target to generate assembly for a file
test/CPPUnit.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/CPPUnit.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/test/CPPUnit.cpp.s
.PHONY : test/CPPUnit.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/WolfensteinTest.dir/build.make CMakeFiles/WolfensteinTest.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... WolfensteinTest"
	@echo "... ServerMain"
	@echo "... common/src/Socket/SocketCommunication.o"
	@echo "... common/src/Socket/SocketCommunication.i"
	@echo "... common/src/Socket/SocketCommunication.s"
	@echo "... common/src/Socket/SocketListener.o"
	@echo "... common/src/Socket/SocketListener.i"
	@echo "... common/src/Socket/SocketListener.s"
	@echo "... common/src/Thread/Thread.o"
	@echo "... common/src/Thread/Thread.i"
	@echo "... common/src/Thread/Thread.s"
	@echo "... server/src/Control/Command/PlayerMove.o"
	@echo "... server/src/Control/Command/PlayerMove.i"
	@echo "... server/src/Control/Command/PlayerMove.s"
	@echo "... server/src/Control/Notification/PlayerConnected.o"
	@echo "... server/src/Control/Notification/PlayerConnected.i"
	@echo "... server/src/Control/Notification/PlayerConnected.s"
	@echo "... server/src/Control/Notification/PlayerDisconnect.o"
	@echo "... server/src/Control/Notification/PlayerDisconnect.i"
	@echo "... server/src/Control/Notification/PlayerDisconnect.s"
	@echo "... server/src/Control/Notification/PlayerUpdatePosition.o"
	@echo "... server/src/Control/Notification/PlayerUpdatePosition.i"
	@echo "... server/src/Control/Notification/PlayerUpdatePosition.s"
	@echo "... server/src/Match/Engine.o"
	@echo "... server/src/Match/Engine.i"
	@echo "... server/src/Match/Engine.s"
	@echo "... server/src/Match/Match.o"
	@echo "... server/src/Match/Match.i"
	@echo "... server/src/Match/Match.s"
	@echo "... server/src/Match/MatchList.o"
	@echo "... server/src/Match/MatchList.i"
	@echo "... server/src/Match/MatchList.s"
	@echo "... server/src/Model/Game/Game.o"
	@echo "... server/src/Model/Game/Game.i"
	@echo "... server/src/Model/Game/Game.s"
	@echo "... server/src/Model/Item/Ammo.o"
	@echo "... server/src/Model/Item/Ammo.i"
	@echo "... server/src/Model/Item/Ammo.s"
	@echo "... server/src/Model/Item/Blood.o"
	@echo "... server/src/Model/Item/Blood.i"
	@echo "... server/src/Model/Item/Blood.s"
	@echo "... server/src/Model/Item/Chest.o"
	@echo "... server/src/Model/Item/Chest.i"
	@echo "... server/src/Model/Item/Chest.s"
	@echo "... server/src/Model/Item/Cross.o"
	@echo "... server/src/Model/Item/Cross.i"
	@echo "... server/src/Model/Item/Cross.s"
	@echo "... server/src/Model/Item/Crown.o"
	@echo "... server/src/Model/Item/Crown.i"
	@echo "... server/src/Model/Item/Crown.s"
	@echo "... server/src/Model/Item/Cup.o"
	@echo "... server/src/Model/Item/Cup.i"
	@echo "... server/src/Model/Item/Cup.s"
	@echo "... server/src/Model/Item/Food.o"
	@echo "... server/src/Model/Item/Food.i"
	@echo "... server/src/Model/Item/Food.s"
	@echo "... server/src/Model/Item/Item.o"
	@echo "... server/src/Model/Item/Item.i"
	@echo "... server/src/Model/Item/Item.s"
	@echo "... server/src/Model/Item/ItemDrop/ItemDrop.o"
	@echo "... server/src/Model/Item/ItemDrop/ItemDrop.i"
	@echo "... server/src/Model/Item/ItemDrop/ItemDrop.s"
	@echo "... server/src/Model/Item/Key.o"
	@echo "... server/src/Model/Item/Key.i"
	@echo "... server/src/Model/Item/Key.s"
	@echo "... server/src/Model/Item/MedKit.o"
	@echo "... server/src/Model/Item/MedKit.i"
	@echo "... server/src/Model/Item/MedKit.s"
	@echo "... server/src/Model/Item/Weapon/Weapon.o"
	@echo "... server/src/Model/Item/Weapon/Weapon.i"
	@echo "... server/src/Model/Item/Weapon/Weapon.s"
	@echo "... server/src/Model/Player/Player.o"
	@echo "... server/src/Model/Player/Player.i"
	@echo "... server/src/Model/Player/Player.s"
	@echo "... server/src/Server/ClientAccepter.o"
	@echo "... server/src/Server/ClientAccepter.i"
	@echo "... server/src/Server/ClientAccepter.s"
	@echo "... server/src/Server/ClientCommunication.o"
	@echo "... server/src/Server/ClientCommunication.i"
	@echo "... server/src/Server/ClientCommunication.s"
	@echo "... server/src/Server/ConnectionHandler.o"
	@echo "... server/src/Server/ConnectionHandler.i"
	@echo "... server/src/Server/ConnectionHandler.s"
	@echo "... server/src/Server/Server.o"
	@echo "... server/src/Server/Server.i"
	@echo "... server/src/Server/Server.s"
	@echo "... serverMain.o"
	@echo "... serverMain.i"
	@echo "... serverMain.s"
	@echo "... test/CPPUnit.o"
	@echo "... test/CPPUnit.i"
	@echo "... test/CPPUnit.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

